name: CI


on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and check
        run: ./gradlew spotlessCheck build
        env:
          BETTER_RSS_MONGO_URI: ${{ secrets.BETTER_RSS_MONGO_URI }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
