name: CI


on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11.0.7, 11]
    name: Build with Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          java-package: jdk
          architecture: x64
      - name: Build and check
        run: ./gradlew spotlessCheck build
        env:
          BETTER_RSS_MONGO_URI: ${{ secrets.BETTER_RSS_MONGO_URI }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
      - name: Upload reports
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: ${{ github.workspace }}/build/reports
        if: ${{ always() }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Setup Google Cloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '301.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Substitute environment variables
        run: envsubst < ./src/main/appengine/app.tpl.yaml > src/main/appengine/app.yaml
        env:
          BETTER_RSS_MONGO_URI: ${{ secrets.BETTER_RSS_MONGO_URI }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
      - name: Deploy
        run: ./gradlew build appengineDeploy
